# Day 27 — Broadcasting & Indexing
 
**Week 5: NumPy — Numerical Computing Foundation**
 
Topics covered: broadcasting rules, basic indexing, slicing, fancy indexing, boolean indexing, `np.ix_`, `np.newaxis`, `Ellipsis`, views vs copies, `np.take`, `np.put`, `np.compress`, advanced multi-dimensional indexing.
 
---

### Q1. Basic 1D Slicing
Create an array of integers from 0 to 19. Using only slicing (no loops), extract:
- Elements from index 3 to 10
- Every third element
- The last 5 elements
- Elements from index 2 to 15 in steps of 3
- The entire array reversed


In [1]:
# Q1: Basic 1D slicing on a 0–19 integer array

import numpy as np

arr = np.arange(20)
print("Original array:", arr)

# Elements from index 3 to 10 (exclusive of 10)
slice1 = arr[3:10]
print("Index 3 to 10:", slice1)

# Every third element
slice2 = arr[::3]
print("Every third element:", slice2)

# Last 5 elements
slice3 = arr[-5:]
print("Last 5 elements:", slice3)

# Index 2 to 15 in steps of 3
slice4 = arr[2:15:3]
print("Index 2 to 15, step 3:", slice4)

# Entire array reversed
slice5 = arr[::-1]
print("Reversed:", slice5)

Original array: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
Index 3 to 10: [3 4 5 6 7 8 9]
Every third element: [ 0  3  6  9 12 15 18]
Last 5 elements: [15 16 17 18 19]
Index 2 to 15, step 3: [ 2  5  8 11 14]
Reversed: [19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1  0]


### How it works

- `np.arange(20)` creates integers from 0 to 19.
- Slicing syntax is `arr[start:stop:step]`. Any part can be omitted.
- `arr[3:10]` → starts at index 3, stops **before** index 10.
- `arr[::3]` → no start/stop means the full array; step 3 picks every 3rd item.
- `arr[-5:]` → negative index counts from the end; `-5` means 5 from the last.
- `arr[2:15:3]` → starts at 2, stops before 15, takes every 3rd.
- `arr[::-1]` → step of `-1` walks the array backwards — the classic reversal trick.

**Key takeaway:** NumPy slicing (`start:stop:step`) lets you extract sub-arrays in one expression without any loops.

### Q2. 2D Slicing
Create a 6×6 matrix of integers from 1 to 36. Using slicing, extract:
- The first 3 rows
- The last 2 columns
- A 3×3 sub-matrix from the center
- Every other row and every other column simultaneously
- The main diagonal elements (using `np.diag`)


In [2]:
# Q2: 2D slicing on a 6x6 matrix of 1–36

import numpy as np

mat = np.arange(1, 37).reshape(6, 6)
print("Original matrix:\n", mat)

# First 3 rows
rows3 = mat[:3, :]
print("\nFirst 3 rows:\n", rows3)

# Last 2 columns
cols2 = mat[:, -2:]
print("\nLast 2 columns:\n", cols2)

# 3x3 sub-matrix from the center (rows 1-4, cols 1-4 → middle 3x3 = rows 1:4, cols 1:4)
center = mat[1:4, 1:4]
print("\n3x3 center sub-matrix:\n", center)

# Every other row and every other column simultaneously
alt = mat[::2, ::2]
print("\nEvery other row & column:\n", alt)

# Main diagonal elements
diag = np.diag(mat)
print("\nMain diagonal:", diag)

Original matrix:
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]

First 3 rows:
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]]

Last 2 columns:
 [[ 5  6]
 [11 12]
 [17 18]
 [23 24]
 [29 30]
 [35 36]]

3x3 center sub-matrix:
 [[ 8  9 10]
 [14 15 16]
 [20 21 22]]

Every other row & column:
 [[ 1  3  5]
 [13 15 17]
 [25 27 29]]

Main diagonal: [ 1  8 15 22 29 36]


### How it works

- A 2D NumPy slice uses `mat[row_slice, col_slice]` — two parts separated by a comma.
- `mat[:3, :]` → take rows 0–2, all columns (`:` alone means "everything").
- `mat[:, -2:]` → all rows, last 2 columns (negative index counts from the end).
- `mat[1:4, 1:4]` → rows 1–3 and columns 1–3 form the center 3×3 block of a 6×6 grid.
- `mat[::2, ::2]` → step-2 on both axes at once; picks rows 0,2,4 and cols 0,2,4.
- `np.diag(mat)` extracts the top-left → bottom-right diagonal as a 1D array.

**Key takeaway:** 2D slicing extends 1D syntax by adding a second `start:stop:step` after a comma — one slice per axis.

### Q3. View vs Copy in Slicing
Create a 1D array `a = np.arange(10)`. Create `b = a[2:7]` (a slice). Modify `b[0] = 99`. Print `a` — does it change? Now create `c = a[2:7].copy()`. Modify `c[0] = 77`. Print `a` again. Explain the view/copy distinction and when each matters.

In [3]:
# Q3: View vs copy behaviour in NumPy slicing

import numpy as np

a = np.arange(10)
print("Original a:", a)

# b is a VIEW — shares memory with a
b = a[2:7]
b[0] = 99
print("\nAfter modifying b[0] = 99:")
print("b:", b)
print("a:", a)          # a[2] also changed — same memory!
print("b shares memory with a:", np.shares_memory(a, b))

# c is a COPY — independent array
c = a[2:7].copy()
c[0] = 77
print("\nAfter modifying c[0] = 77:")
print("c:", c)
print("a:", a)          # a is unchanged
print("c shares memory with a:", np.shares_memory(a, c))

Original a: [0 1 2 3 4 5 6 7 8 9]

After modifying b[0] = 99:
b: [99  3  4  5  6]
a: [ 0  1 99  3  4  5  6  7  8  9]
b shares memory with a: True

After modifying c[0] = 77:
c: [77  3  4  5  6]
a: [ 0  1 99  3  4  5  6  7  8  9]
c shares memory with a: False


### How it works

- Basic slicing in NumPy returns a **view** — not a new array, but a window into the same memory block.
- Think of a view like a nickname: changing what the nickname refers to changes the real thing.
- So `b = a[2:7]` and `a` point to the same data; modifying `b[0]` also changes `a[2]`.
- `.copy()` creates a completely independent array with its own memory — changes to `c` never affect `a`.
- `np.shares_memory(x, y)` is a handy way to check whether two arrays share the same data.
- **When does this matter?** Views are memory-efficient for large arrays. Copies are safe when you need to modify data without touching the original.

**Key takeaway:** NumPy slices are views by default — call `.copy()` explicitly when you need an independent array.

### Q4. Fancy Indexing with Integer Arrays
Create a 1D array of 10 elements. Use an integer index array `[0, 3, 7, 9]` to select specific elements. Then use a 2D index array `[[0, 1], [3, 4]]` and observe the shape of the result. Demonstrate that fancy indexing always returns a **copy**, not a view.

In [4]:
# Q4: Fancy indexing with integer arrays

import numpy as np

arr = np.arange(10, 110, 10)  # [10, 20, 30, ..., 100]
print("Original array:", arr)

# 1D fancy indexing — pick specific elements by index list
idx = [0, 3, 7, 9]
selected = arr[idx]
print("\nFancy index [0, 3, 7, 9]:", selected)

# 2D index array — result shape matches the index array shape
idx_2d = [[0, 1], [3, 4]]
selected_2d = arr[idx_2d]
print("\n2D index array [[0,1],[3,4]]:")
print(selected_2d)
print("Shape of result:", selected_2d.shape)  # (2, 2)

# Prove fancy indexing returns a COPY, not a view
fancy = arr[[0, 3, 7, 9]]
fancy[0] = 999
print("\nAfter modifying fancy[0] = 999:")
print("fancy:", fancy)
print("arr:", arr)                              # arr is unchanged
print("Shares memory:", np.shares_memory(arr, fancy))

Original array: [ 10  20  30  40  50  60  70  80  90 100]

Fancy index [0, 3, 7, 9]: [ 10  40  80 100]

2D index array [[0,1],[3,4]]:
[[10 20]
 [40 50]]
Shape of result: (2, 2)

After modifying fancy[0] = 999:
fancy: [999  40  80 100]
arr: [ 10  20  30  40  50  60  70  80  90 100]
Shares memory: False


### How it works

- **Fancy indexing** means passing a list (or array) of integers as the index instead of a slice.
- `arr[[0, 3, 7, 9]]` picks elements at those exact positions — like choosing specific seats by number.
- When the index array is 2D (shape `(2, 2)`), the output shape also becomes `(2, 2)` — NumPy maps each index to its element and arranges them in the same shape as the index array.
- Unlike slicing, fancy indexing **always returns a copy** — modifying the result never affects the original.
- `np.shares_memory()` confirms this: it returns `False` for fancy-indexed arrays.

**Key takeaway:** Fancy indexing lets you select elements in any order and shape, but always gives you a copy — so edits are safe but memory usage is higher than views.

### Q5. Fancy Indexing on 2D Arrays
Create a 5×5 matrix. Select:
- Rows 0, 2, and 4 (all columns) using fancy indexing
- Elements at positions `(0,0)`, `(1,2)`, `(3,4)` using two index arrays
- A 3×3 sub-matrix using `np.ix_([0,2,4], [1,3,4])`
Print each result with its shape.

In [5]:
# Q5: Fancy indexing on a 5x5 2D matrix

import numpy as np

mat = np.arange(1, 26).reshape(5, 5)
print("Matrix:\n", mat)
print("Shape:", mat.shape)

# Rows 0, 2, 4 — all columns
rows = mat[[0, 2, 4], :]
print("\nRows 0, 2, 4:\n", rows)
print("Shape:", rows.shape)          # (3, 5)

# Specific elements at (0,0), (1,2), (3,4) — pair up row and col index arrays
row_idx = [0, 1, 3]
col_idx = [0, 2, 4]
elements = mat[row_idx, col_idx]     # picks (0,0), (1,2), (3,4) — one pair at a time
print("\nElements at (0,0), (1,2), (3,4):", elements)
print("Shape:", elements.shape)      # (3,) — 1D, one value per pair

# 3x3 sub-matrix using np.ix_ — creates an open mesh for cross-product selection
ix = np.ix_([0, 2, 4], [1, 3, 4])
submat = mat[ix]
print("\n3x3 sub-matrix via np.ix_([0,2,4], [1,3,4]):\n", submat)
print("Shape:", submat.shape)        # (3, 3)

Matrix:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
Shape: (5, 5)

Rows 0, 2, 4:
 [[ 1  2  3  4  5]
 [11 12 13 14 15]
 [21 22 23 24 25]]
Shape: (3, 5)

Elements at (0,0), (1,2), (3,4): [ 1  8 20]
Shape: (3,)

3x3 sub-matrix via np.ix_([0,2,4], [1,3,4]):
 [[ 2  4  5]
 [12 14 15]
 [22 24 25]]
Shape: (3, 3)


### How it works

- `mat[[0, 2, 4], :]` picks entire rows by index list — result shape is `(3, 5)`.
- Paired index arrays `mat[[0,1,3], [0,2,4]]` work element-by-element: first pair is `(0,0)`, second is `(1,2)`, third is `(3,4)` — result is 1D with one value per pair.
- `np.ix_` is the key difference: it builds a **mesh** so every row index is combined with every column index — like a multiplication table of positions.
- `np.ix_([0,2,4], [1,3,4])` selects 3 rows × 3 cols = a true `(3, 3)` sub-matrix.
- Think of paired arrays as "pick these exact seats" vs `np.ix_` as "pick all seats in these rows AND these columns".

**Key takeaway:** Use paired index arrays to pick specific `(row, col)` points; use `np.ix_` when you want every combination of chosen rows and columns as a sub-matrix.

### Q6. Boolean Indexing — Filtering
Create a 1D array of 15 random integers between 0 and 50. Using boolean indexing:
- Select all values greater than 25
- Select all even values
- Select values in the range [10, 30] inclusive
- Replace all values less than 10 with 0 (in-place using boolean index assignment)

In [6]:
# Q6: Boolean indexing and filtering on a 1D array

import numpy as np

rng = np.random.default_rng(42)          # fixed seed for reproducibility
arr = rng.integers(0, 51, size=15)
print("Original array:", arr)

# Values greater than 25
gt25 = arr[arr > 25]
print("\nValues > 25:", gt25)

# Even values (remainder when divided by 2 is 0)
evens = arr[arr % 2 == 0]
print("Even values:", evens)

# Values in range [10, 30] inclusive — combine two conditions with &
in_range = arr[(arr >= 10) & (arr <= 30)]
print("Values in [10, 30]:", in_range)

# Replace values less than 10 with 0 — in-place boolean assignment
arr_copy = arr.copy()                    # keep original intact for comparison
arr_copy[arr_copy < 10] = 0
print("\nAfter replacing values < 10 with 0:", arr_copy)

Original array: [ 4 39 33 22 22 43  4 35 10  4 26 49 37 38 36]

Values > 25: [39 33 43 35 26 49 37 38 36]
Even values: [ 4 22 22  4 10  4 26 38 36]
Values in [10, 30]: [22 22 10 26]

After replacing values < 10 with 0: [ 0 39 33 22 22 43  0 35 10  0 26 49 37 38 36]


### How it works

- Boolean indexing works in two steps: first create a **boolean mask** (an array of True/False), then use it to filter.
- `arr > 25` produces a mask like `[False, True, True, ...]`; passing it into `arr[...]` keeps only the `True` positions.
- `arr % 2 == 0` checks divisibility by 2 — True for every even number.
- Combining two conditions requires `&` (AND) with each condition in its own parentheses: `(arr >= 10) & (arr <= 30)`. Using `and` (Python keyword) raises an error on arrays.
- Boolean assignment `arr[arr < 10] = 0` modifies the array **in-place** at every `True` position — no loop needed.

**Key takeaway:** Boolean indexing lets you filter or overwrite elements using conditions directly — the mask selects positions, and assignment writes values to exactly those positions.

### Q7. Boolean Indexing on 2D Arrays
Create a 4×5 matrix of random integers. Using boolean indexing:
- Select all elements greater than the array's mean
- Replace all elements above the 75th percentile with the value 100
- Find which rows have all positive values (use `np.all` along axis=1)
- Find which columns have at least one value greater than 90

In [7]:
# Q7: Boolean indexing on a 4x5 2D matrix

import numpy as np

rng = np.random.default_rng(7)
mat = rng.integers(0, 101, size=(4, 5))
print("Matrix:\n", mat)
print("Shape:", mat.shape)

# Elements greater than the array mean
mean_val = mat.mean()
print(f"\nArray mean: {mean_val:.2f}")
above_mean = mat[mat > mean_val]          # returns 1D array of matching values
print("Elements > mean:", above_mean)

# Replace elements above 75th percentile with 100 (in-place)
p75 = np.percentile(mat, 75)
print(f"\n75th percentile: {p75}")
mat_copy = mat.copy()
mat_copy[mat_copy > p75] = 100
print("After replacing values above 75th percentile with 100:\n", mat_copy)

# Rows where ALL values are positive (>0) — axis=1 checks across each row
all_positive_rows = np.all(mat > 0, axis=1)  # shape (4,) — one bool per row
print("\nRow mask (all values > 0):", all_positive_rows)
print("Row indices with all positive values:", np.where(all_positive_rows)[0])

# Columns where AT LEAST ONE value > 90 — axis=0 checks down each column
any_gt90_cols = np.any(mat > 90, axis=0)     # shape (5,) — one bool per col
print("\nColumn mask (any value > 90):", any_gt90_cols)
print("Column indices with at least one value > 90:", np.where(any_gt90_cols)[0])

Matrix:
 [[95 63 69 90 58]
 [78 84 22  5 30]
 [28 88 92  0 50]
 [82 13 80 12 47]]
Shape: (4, 5)

Array mean: 54.30
Elements > mean: [95 63 69 90 58 78 84 88 92 82 80]

75th percentile: 82.5
After replacing values above 75th percentile with 100:
 [[100  63  69 100  58]
 [ 78 100  22   5  30]
 [ 28 100 100   0  50]
 [ 82  13  80  12  47]]

Row mask (all values > 0): [ True  True False  True]
Row indices with all positive values: [0 1 3]

Column mask (any value > 90): [ True False  True False False]
Column indices with at least one value > 90: [0 2]


### How it works

- `mat[mat > mean_val]` applies a 2D boolean mask to a 2D array — the result is always **flattened to 1D** because the selected elements may not form a rectangle.
- `np.percentile(mat, 75)` finds the value below which 75% of all elements fall; in-place assignment `mat_copy[mat_copy > p75] = 100` overwrites every element above it.
- `np.all(mat > 0, axis=1)` checks each **row** (axis=1 moves along columns): returns `True` for a row only if every element in it is positive.
- `np.any(mat > 90, axis=0)` checks each **column** (axis=0 moves down rows): returns `True` for a column if even one element exceeds 90.
- `np.where(mask)[0]` converts a boolean mask into the actual integer indices — useful for reporting positions.

**Key takeaway:** Use `np.all` / `np.any` with `axis=` to reduce a 2D boolean mask row-wise or column-wise — `axis=1` collapses columns (gives one result per row), `axis=0` collapses rows (gives one result per column).

### Q8. `np.newaxis` and Dimension Expansion
Explain the effect of `np.newaxis` (alias for `None`). Given a 1D array of shape `(5,)`, use `np.newaxis` to convert it to:
- Shape `(1, 5)` — row vector
- Shape `(5, 1)` — column vector
Then use both in a subtraction to create a 5×5 outer difference matrix (no loops).

In [8]:
# Q8: np.newaxis for dimension expansion and outer difference matrix

import numpy as np

a = np.array([10, 20, 30, 40, 50])
print("Original array:", a)
print("Original shape:", a.shape)        # (5,)

# Convert to row vector — insert new axis at position 0
row_vec = a[np.newaxis, :]               # same as a[None, :]
print("\nRow vector:", row_vec)
print("Row vector shape:", row_vec.shape)   # (1, 5)

# Convert to column vector — insert new axis at position 1
col_vec = a[:, np.newaxis]               # same as a[:, None]
print("\nColumn vector:\n", col_vec)
print("Column vector shape:", col_vec.shape)  # (5, 1)

# 5x5 outer difference matrix — broadcasting does the nested loop for us
# col_vec (5,1) - row_vec (1,5) → (5,5) via broadcasting
diff_matrix = col_vec - row_vec
print("\n5x5 outer difference matrix (col - row):\n", diff_matrix)
print("Shape:", diff_matrix.shape)       # (5, 5)

Original array: [10 20 30 40 50]
Original shape: (5,)

Row vector: [[10 20 30 40 50]]
Row vector shape: (1, 5)

Column vector:
 [[10]
 [20]
 [30]
 [40]
 [50]]
Column vector shape: (5, 1)

5x5 outer difference matrix (col - row):
 [[  0 -10 -20 -30 -40]
 [ 10   0 -10 -20 -30]
 [ 20  10   0 -10 -20]
 [ 30  20  10   0 -10]
 [ 40  30  20  10   0]]
Shape: (5, 5)


### How it works

- A 1D array of shape `(5,)` has only one axis. NumPy cannot broadcast it against another 1D array to make a 2D result — dimensions must align.
- `np.newaxis` (same as `None`) inserts a length-1 axis at the chosen position without copying data.
- `a[np.newaxis, :]` → shape `(1, 5)`: one row, five columns — a **row vector**.
- `a[:, np.newaxis]` → shape `(5, 1)`: five rows, one column — a **column vector**.
- Subtracting `(5, 1)` from `(1, 5)`: NumPy stretches the row vector across 5 rows and the column vector across 5 columns, producing a `(5, 5)` matrix where `result[i, j] = a[i] - a[j]`.
- This is the **outer difference** — equivalent to a nested loop but computed in one expression.

**Key takeaway:** `np.newaxis` promotes a 1D array into a row or column vector; combining both orientations in one operation triggers broadcasting to produce a full outer product or difference matrix with no loops.

### Q9. Ellipsis (`...`) in Indexing
Create a 4D array of shape `(2, 3, 4, 5)`. Use `Ellipsis` to:
- Select all elements in the last dimension at index 2: `arr[..., 2]`
- Select all elements in the first dimension at index 1: `arr[1, ...]`
- Select a slice across the middle dimensions: `arr[0, ..., -1]`
Print each result's shape and explain what `...` replaces.

In [9]:
# Q9: Ellipsis indexing on a 4D array

import numpy as np

arr = np.arange(120).reshape(2, 3, 4, 5)
print("Array shape:", arr.shape)         # (2, 3, 4, 5)

# arr[..., 2] — fix last dimension at index 2, keep all others
last_dim = arr[..., 2]
print("\narr[..., 2]")
print("Shape:", last_dim.shape)          # (2, 3, 4) — last axis collapsed to index 2
print("... replaced: axis 0, 1, 2 (all rows/cols/depths kept)")

# arr[1, ...] — fix first dimension at index 1, keep all others
first_dim = arr[1, ...]
print("\narr[1, ...]")
print("Shape:", first_dim.shape)         # (3, 4, 5) — first axis collapsed to index 1
print("... replaced: axis 1, 2, 3 (all remaining axes kept)")

# arr[0, ..., -1] — fix first dim at 0 and last dim at -1, keep middle dims
middle = arr[0, ..., -1]
print("\narr[0, ..., -1]")
print("Shape:", middle.shape)            # (3, 4) — first and last axes collapsed
print("... replaced: axis 1, 2 (the two middle axes kept)")

Array shape: (2, 3, 4, 5)

arr[..., 2]
Shape: (2, 3, 4)
... replaced: axis 0, 1, 2 (all rows/cols/depths kept)

arr[1, ...]
Shape: (3, 4, 5)
... replaced: axis 1, 2, 3 (all remaining axes kept)

arr[0, ..., -1]
Shape: (3, 4)
... replaced: axis 1, 2 (the two middle axes kept)


### How it works

- `...` (Ellipsis) is a placeholder that means **"fill in as many `:` as needed"** to account for all remaining axes.
- For a `(2, 3, 4, 5)` array, writing `arr[..., 2]` is the same as `arr[:, :, :, 2]` — three colons filled in automatically.
- `arr[1, ...]` equals `arr[1, :, :, :]` — Ellipsis fills the last three axes.
- `arr[0, ..., -1]` equals `arr[0, :, :, -1]` — Ellipsis fills the two middle axes.
- Fixing one axis with a single integer **removes** that axis from the output shape; `:` keeps it.
- Ellipsis is especially useful when you do not know in advance how many dimensions an array has — your indexing expression stays the same regardless.

**Key takeaway:** `...` auto-fills the right number of `:` for all unspecified axes — it makes indexing expressions shorter and works on arrays of any dimensionality.

### Q10. Broadcasting Rule 1 — Scalar
Demonstrate broadcasting by adding a scalar to a 3×4 array. Then show that the equivalent without broadcasting would require `np.full((3,4), scalar)`. Confirm both give the same result.

In [10]:
# Q10: Broadcasting — scalar to 2D array

import numpy as np

mat = np.arange(1, 13).reshape(3, 4)
scalar = 10
print("Original matrix:\n", mat)
print("Shape:", mat.shape)               # (3, 4)

# Broadcasting: scalar is stretched across every element automatically
result_broadcast = mat + scalar
print("\nmat + 10 (broadcasting):\n", result_broadcast)
print("Shape:", result_broadcast.shape)  # (3, 4)

# Equivalent without broadcasting — manually expand scalar to same shape
full_mat = np.full((3, 4), scalar)       # creates a (3,4) array filled with 10
print("\nnp.full((3,4), 10):\n", full_mat)

result_manual = mat + full_mat
print("\nmat + np.full((3,4), 10):\n", result_manual)

# Confirm both results are identical
print("\nResults are equal:", np.array_equal(result_broadcast, result_manual))

Original matrix:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Shape: (3, 4)

mat + 10 (broadcasting):
 [[11 12 13 14]
 [15 16 17 18]
 [19 20 21 22]]
Shape: (3, 4)

np.full((3,4), 10):
 [[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]

mat + np.full((3,4), 10):
 [[11 12 13 14]
 [15 16 17 18]
 [19 20 21 22]]

Results are equal: True


### How it works

- A scalar has **no dimensions** — shape `()`. NumPy's broadcasting rules stretch it to match any array shape automatically.
- Think of it like painting every cell of a grid the same colour — you specify the colour once, not once per cell.
- Internally, NumPy behaves as if it created a `(3, 4)` array filled with `10` and added it — but without actually allocating that memory.
- `np.full((3, 4), 10)` makes that implicit expansion **explicit**: a real array of the target shape filled with the scalar.
- `np.array_equal` confirms both paths produce identical values.

**Key takeaway:** Broadcasting with a scalar is the simplest case — NumPy silently stretches it to every position, saving both code and memory compared to manually building a full array.

### Q11. Broadcasting Rule 2 — 1D with 2D
Given a 2D array of shape `(4, 3)` and a 1D array of shape `(3,)`, add them together. Explain step-by-step which broadcasting rule applies. Then show that a 1D array of shape `(4,)` cannot be broadcast along columns — and how to fix it with `np.newaxis` or `reshape`.

In [11]:
# Q11: Broadcasting 1D (3,) with 2D (4,3) — and fixing the (4,) mismatch

import numpy as np

mat = np.arange(1, 13).reshape(4, 3)    # shape (4, 3)
row = np.array([10, 20, 30])            # shape (3,)
print("Matrix shape:", mat.shape)
print("Matrix:\n", mat)
print("\nRow array:", row, "| Shape:", row.shape)

# (3,) + (4,3) — works: (3,) is treated as (1,3) then stretched to (4,3)
result = mat + row
print("\nmat + row (broadcasting (3,) → (4,3)):\n", result)
print("Result shape:", result.shape)    # (4, 3)

# -----------------------------------------------------------------------
# Now try a (4,) array — this CANNOT broadcast with (4,3) directly
col = np.array([100, 200, 300, 400])    # shape (4,)
print("\nColumn array:", col, "| Shape:", col.shape)

try:
    bad = mat + col                     # raises ValueError
except ValueError as e:
    print("\nError adding (4,3) + (4,) directly:", e)

# Fix 1: np.newaxis — convert (4,) to (4,1), then it stretches to (4,3)
col_fixed = col[:, np.newaxis]          # shape (4, 1)
print("\ncol[:, np.newaxis] shape:", col_fixed.shape)
result_col = mat + col_fixed
print("mat + col[:, np.newaxis]:\n", result_col)
print("Result shape:", result_col.shape)  # (4, 3)

# Fix 2: reshape — same effect as np.newaxis
col_reshaped = col.reshape(4, 1)
print("\nSame result with col.reshape(4,1):", np.array_equal(result_col, mat + col_reshaped))

Matrix shape: (4, 3)
Matrix:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

Row array: [10 20 30] | Shape: (3,)

mat + row (broadcasting (3,) → (4,3)):
 [[11 22 33]
 [14 25 36]
 [17 28 39]
 [20 31 42]]
Result shape: (4, 3)

Column array: [100 200 300 400] | Shape: (4,)

Error adding (4,3) + (4,) directly: operands could not be broadcast together with shapes (4,3) (4,) 

col[:, np.newaxis] shape: (4, 1)
mat + col[:, np.newaxis]:
 [[101 102 103]
 [204 205 206]
 [307 308 309]
 [410 411 412]]
Result shape: (4, 3)

Same result with col.reshape(4,1): True


### How it works

- NumPy aligns shapes **from the right** before broadcasting.
- `(4, 3)` vs `(3,)` → pad left: `(4, 3)` vs `(1, 3)` → stretch the `1` to `4` → result `(4, 3)`. This works.
- `(4, 3)` vs `(4,)` → pad left: `(4, 3)` vs `(1, 4)` → right-most dimensions are `3` vs `4` — they do not match and neither is `1`, so NumPy raises a `ValueError`.
- The fix is to make the `(4,)` array a **column** by adding a new axis: `col[:, np.newaxis]` gives shape `(4, 1)`. Now `(4, 3)` vs `(4, 1)` → stretch the `1` column across 3 columns → result `(4, 3)`.
- `reshape(4, 1)` achieves the exact same shape change as `np.newaxis`.

**Key takeaway:** Broadcasting aligns from the right — a `(4,)` array is treated as a row `(1, 4)`, not a column; use `np.newaxis` or `reshape(-1, 1)` to turn it into a `(4, 1)` column so it broadcasts down the rows.

### Q12. Broadcasting Rule 3 — Column Vector with Row Vector
Create a column vector `[[0], [1], [2], [3]]` (shape `(4,1)`) and a row vector `[10, 20, 30]` (shape `(1,3)` or `(3,)`). Add them without loops to produce a `(4,3)` matrix. Show this is equivalent to the outer sum.

In [12]:
# Q12: Broadcasting column vector (4,1) + row vector (3,) → (4,3) outer sum

import numpy as np

col = np.array([[0], [1], [2], [3]])    # shape (4, 1)
row = np.array([10, 20, 30])            # shape (3,) — treated as (1, 3)
print("Column vector shape:", col.shape)
print("Column vector:\n", col)
print("\nRow vector shape:", row.shape)
print("Row vector:", row)

# Broadcasting: (4,1) + (1,3) → (4,3)
result = col + row
print("\nBroadcast result (col + row):\n", result)
print("Result shape:", result.shape)    # (4, 3)

# Equivalent: np.add.outer — computes the outer sum explicitly
outer = np.add.outer(col.ravel(), row)  # ravel() flattens (4,1) → (4,)
print("\nnp.add.outer result:\n", outer)
print("Outer shape:", outer.shape)      # (4, 3)

# Confirm both are identical
print("\nBroadcast == outer sum:", np.array_equal(result, outer))

# Visualise what happened — each cell is col[i] + row[j]
print("\nManual check — cell (2, 1) = col[2] + row[1] =", col[2, 0], "+", row[1], "=", result[2, 1])

Column vector shape: (4, 1)
Column vector:
 [[0]
 [1]
 [2]
 [3]]

Row vector shape: (3,)
Row vector: [10 20 30]

Broadcast result (col + row):
 [[10 20 30]
 [11 21 31]
 [12 22 32]
 [13 23 33]]
Result shape: (4, 3)

np.add.outer result:
 [[10 20 30]
 [11 21 31]
 [12 22 32]
 [13 23 33]]
Outer shape: (4, 3)

Broadcast == outer sum: True

Manual check — cell (2, 1) = col[2] + row[1] = 2 + 20 = 22


### How it works

- NumPy aligns shapes from the right: `(4, 1)` vs `(3,)` → pad → `(4, 1)` vs `(1, 3)`.
- The `1` in each shape gets **stretched** to match the other dimension: col stretches to `(4, 3)`, row stretches to `(4, 3)`.
- Every cell `result[i, j]` equals `col[i] + row[j]` — this is the definition of an **outer sum**.
- `np.add.outer` computes the same thing explicitly: for every pair `(i, j)`, add the two values.
- No loops, no manual tiling — broadcasting handles the expansion in one expression.

**Key takeaway:** A `(4, 1)` column and a `(1, 3)` row broadcast together by stretching each `1`-sized axis — every row gets the same column offset and every column gets the same row offset, producing a full outer sum.

### Q13. Broadcasting for Normalization
Given a 2D dataset of shape `(5, 4)`, subtract the column means (axis=0) from each row, then divide by the column standard deviations — all in two broadcasting lines. Verify the result has mean ≈ 0 and std ≈ 1 per column.

In [13]:
# Q13: Column-wise normalization (z-score) using broadcasting

import numpy as np

rng = np.random.default_rng(21)
data = rng.integers(10, 100, size=(5, 4)).astype(float)
print("Original data:\n", data)
print("Shape:", data.shape)              # (5, 4)

# Column means and stds — keepdims=True keeps shape (1, 4) for broadcasting
col_mean = data.mean(axis=0, keepdims=True)   # shape (1, 4)
col_std  = data.std(axis=0, keepdims=True)    # shape (1, 4)
print("\nColumn means:", col_mean)
print("Column stds: ", col_std)

# Normalize: subtract mean then divide by std — both broadcast (1,4) → (5,4)
normalized = (data - col_mean) / col_std
print("\nNormalized data:\n", np.round(normalized, 4))
print("Shape:", normalized.shape)        # (5, 4)

# Verify: column means ≈ 0 and column stds ≈ 1
print("\nColumn means after normalization:", np.round(normalized.mean(axis=0), 10))
print("Column stds  after normalization:", np.round(normalized.std(axis=0), 10))

Original data:
 [[37. 80. 44. 64.]
 [51. 73. 40. 18.]
 [36. 66. 65. 98.]
 [31. 48. 95. 20.]
 [73. 96. 92. 70.]]
Shape: (5, 4)

Column means: [[45.6 72.6 67.2 54. ]]
Column stds:  [[15.22629305 15.81897595 23.1119017  30.80259729]]

Normalized data:
 [[-0.5648  0.4678 -1.0038  0.3246]
 [ 0.3546  0.0253 -1.1769 -1.1687]
 [-0.6305 -0.4172 -0.0952  1.4285]
 [-0.9589 -1.5551  1.2028 -1.1038]
 [ 1.7995  1.4792  1.073   0.5194]]
Shape: (5, 4)

Column means after normalization: [-0.  0. -0. -0.]
Column stds  after normalization: [1. 1. 1. 1.]


### How it works

- `data.mean(axis=0, keepdims=True)` computes the mean **down each column** and keeps the result as shape `(1, 4)` instead of `(4,)` — the `keepdims=True` is the key detail.
- Without `keepdims=True`, the mean would be shape `(4,)` — it still broadcasts, but `keepdims=True` makes the intent explicit and avoids surprises in higher dimensions.
- `(5, 4) - (1, 4)` → the `(1, 4)` mean stretches across all 5 rows, subtracting the correct column mean from every element in that column.
- Dividing by `col_std` (also `(1, 4)`) scales each column independently.
- The result is a **z-score normalization**: each column now has mean 0 and standard deviation 1, confirmed by the final print.

**Key takeaway:** Use `axis=0, keepdims=True` to compute column statistics as shape `(1, 4)` — this lets them broadcast cleanly against the original `(5, 4)` data without any reshape or newaxis call.

### Q14. Outer Product via Broadcasting
Without using `np.outer`, compute the outer product of two 1D arrays `a = [1, 2, 3, 4]` and `b = [10, 20, 30]` using broadcasting (reshape one to a column vector). Compare to `np.outer(a, b)` and verify they match.

In [14]:
# Q14: Outer product via broadcasting vs np.outer

import numpy as np

a = np.array([1, 2, 3, 4])             # shape (4,)
b = np.array([10, 20, 30])             # shape (3,)
print("a:", a, "| shape:", a.shape)
print("b:", b, "| shape:", b.shape)

# Reshape a to column vector (4,1) so it broadcasts against b (3,) → (4,3)
a_col = a[:, np.newaxis]               # shape (4, 1)
print("\na as column vector shape:", a_col.shape)

outer_broadcast = a_col * b            # (4,1) * (3,) → (4,3)
print("\nOuter product via broadcasting:\n", outer_broadcast)
print("Shape:", outer_broadcast.shape) # (4, 3)

# np.outer for direct comparison
outer_np = np.outer(a, b)
print("\nnp.outer(a, b):\n", outer_np)
print("Shape:", outer_np.shape)        # (4, 3)

# Verify both are identical
print("\nResults match:", np.array_equal(outer_broadcast, outer_np))

# Manual check — cell (i,j) = a[i] * b[j]
print("\nManual check — cell (2,1) = a[2] * b[1] =", a[2], "*", b[1], "=", outer_broadcast[2, 1])

a: [1 2 3 4] | shape: (4,)
b: [10 20 30] | shape: (3,)

a as column vector shape: (4, 1)

Outer product via broadcasting:
 [[ 10  20  30]
 [ 20  40  60]
 [ 30  60  90]
 [ 40  80 120]]
Shape: (4, 3)

np.outer(a, b):
 [[ 10  20  30]
 [ 20  40  60]
 [ 30  60  90]
 [ 40  80 120]]
Shape: (4, 3)

Results match: True

Manual check — cell (2,1) = a[2] * b[1] = 3 * 20 = 60


### How it works

- The outer product of two 1D arrays produces a 2D matrix where `result[i, j] = a[i] * b[j]` — every element of `a` is multiplied by every element of `b`.
- Reshaping `a` to `(4, 1)` turns it into a column vector. Broadcasting then stretches it to `(4, 3)` and `b` from `(3,)` to `(4, 3)` — matching shapes for element-wise multiplication.
- `np.outer` does exactly the same thing internally — it just handles the reshape for you.
- Think of it like a multiplication table: rows are values of `a`, columns are values of `b`, and each cell is their product.

**Key takeaway:** The outer product is just broadcasting with one array as a column `(n, 1)` and the other as a row `(m,)` — multiplying them gives every pairwise product in a single `(n, m)` matrix.

### Q15. Broadcasting Gotcha — When It Fails
Deliberately attempt to broadcast:
- Shape `(3, 4)` with shape `(4, 3)` (should fail)
- Shape `(3,)` with shape `(4,)` (should fail)
Catch the `ValueError`, read the error message, and explain the broadcasting rule that was violated in each case.

In [15]:
# Q15: Broadcasting failures — understanding why they fail

import numpy as np

# --- Case 1: (3,4) + (4,3) ---
a = np.ones((3, 4))
b = np.ones((4, 3))
print("Case 1:")
print("  a shape:", a.shape)            # (3, 4)
print("  b shape:", b.shape)            # (4, 3)

try:
    result = a + b
except ValueError as e:
    print("  Error:", e)

# Why it fails — align from the right:
#   (3, 4)
#   (4, 3)
#    ^  ^— rightmost: 4 vs 3 — neither is 1 → FAIL
print("  Rule violated: rightmost dims 4 vs 3 — neither is 1, cannot stretch")

# How to fix — reshape b to (3,4) if logical context allows
b_fixed = b.T                           # transpose (4,3) → (3,4)
print("  Fixed with b.T shape:", b_fixed.shape)
print("  a + b.T result shape:", (a + b_fixed).shape)

print()

# --- Case 2: (3,) + (4,) ---
c = np.array([1, 2, 3])                # shape (3,)
d = np.array([10, 20, 30, 40])         # shape (4,)
print("Case 2:")
print("  c shape:", c.shape)            # (3,)
print("  d shape:", d.shape)            # (4,)

try:
    result = c + d
except ValueError as e:
    print("  Error:", e)

# Why it fails — align from the right:
#   (3,)
#   (4,)
#    ^— only one dim each: 3 vs 4 — neither is 1 → FAIL
print("  Rule violated: only dim is 3 vs 4 — neither is 1, cannot stretch")

# How to fix — make one a column vector so they broadcast to (4,3) outer sum
c_col = c[:, np.newaxis]               # shape (3, 1)
print("  Fixed with c[:,np.newaxis] shape:", c_col.shape)
print("  c_col + d result shape:", (c_col + d).shape)   # (3, 4) outer sum

Case 1:
  a shape: (3, 4)
  b shape: (4, 3)
  Error: operands could not be broadcast together with shapes (3,4) (4,3) 
  Rule violated: rightmost dims 4 vs 3 — neither is 1, cannot stretch
  Fixed with b.T shape: (3, 4)
  a + b.T result shape: (3, 4)

Case 2:
  c shape: (3,)
  d shape: (4,)
  Error: operands could not be broadcast together with shapes (3,) (4,) 
  Rule violated: only dim is 3 vs 4 — neither is 1, cannot stretch
  Fixed with c[:,np.newaxis] shape: (3, 1)
  c_col + d result shape: (3, 4)


### How it works

- NumPy's broadcasting rule: align shapes **from the right**, then each pair of dimensions must either **match exactly** or one of them must be **1** (the `1` gets stretched).
- **Case 1** — `(3, 4)` vs `(4, 3)`: aligning from the right gives pairs `(4 vs 3)` and `(3 vs 4)`. Neither pair satisfies the rule — no dimension is `1` and the sizes differ. NumPy raises a `ValueError`.
- **Case 2** — `(3,)` vs `(4,)`: both have one dimension, so the only pair is `3 vs 4`. Again, neither is `1` and sizes differ — same failure.
- Transposing `(4, 3)` to `(3, 4)` fixes Case 1 by making shapes identical.
- Adding `np.newaxis` to turn `(3,)` into `(3, 1)` fixes Case 2 by introducing a `1` axis that can stretch against `(4,)` — but the result is now a `(3, 4)` outer sum, not a `(3,)` or `(4,)` array.

**Key takeaway:** Broadcasting fails when aligned dimensions are unequal and neither is `1` — the fix is always to reshape or transpose until every dimension pair is either equal or contains a `1`.

### Q16. `np.take` and `np.put`
Use `np.take` to gather elements from an array at specified indices, with both `axis=None` (flat) and along a specific axis of a 2D array. Use `np.put` to scatter values into an array at specified flat indices. Compare `np.take` vs fancy indexing and note any differences.

In [16]:
# Q16: np.take and np.put — gather and scatter operations

import numpy as np

# -----------------------------------------------------------------------
# np.take — gather elements at given indices
# -----------------------------------------------------------------------
arr = np.array([10, 20, 30, 40, 50, 60])
print("1D array:", arr)

# axis=None: treat array as flat, pick by flat index
taken_flat = np.take(arr, [0, 2, 5])
print("\nnp.take(arr, [0,2,5], axis=None):", taken_flat)

# Fancy indexing equivalent on 1D
fancy_flat = arr[[0, 2, 5]]
print("arr[[0,2,5]] (fancy):            ", fancy_flat)
print("Same result:", np.array_equal(taken_flat, fancy_flat))

# -----------------------------------------------------------------------
# np.take on 2D — along a specific axis
# -----------------------------------------------------------------------
mat = np.arange(1, 13).reshape(3, 4)
print("\n2D matrix:\n", mat)

# axis=0: pick rows 0 and 2
rows = np.take(mat, [0, 2], axis=0)
print("\nnp.take(mat, [0,2], axis=0) — pick rows:\n", rows)
print("Shape:", rows.shape)            # (2, 4)

# axis=1: pick columns 1 and 3
cols = np.take(mat, [1, 3], axis=1)
print("\nnp.take(mat, [1,3], axis=1) — pick columns:\n", cols)
print("Shape:", cols.shape)            # (3, 2)

# Key difference: np.take supports index wrapping (mode='wrap')
wrapped = np.take(arr, [0, 7, -1], mode='wrap')  # index 7 wraps → 7%6=1
print("\nnp.take with mode='wrap', indices [0,7,-1]:", wrapped)
print("(index 7 wraps to position 1, -1 wraps to position 5)")

# -----------------------------------------------------------------------
# np.put — scatter values into flat indices (in-place)
# -----------------------------------------------------------------------
target = np.zeros(8, dtype=int)
print("\nBefore np.put:", target)

np.put(target, [1, 3, 6], [99, 88, 77])   # put values at flat indices
print("After np.put(target, [1,3,6], [99,88,77]):", target)

# np.put also supports mode='wrap'
target2 = np.zeros(6, dtype=int)
np.put(target2, [0, 7, 13], [11, 22, 33], mode='wrap')  # 7%6=1, 13%6=1→ overwrites
print("\nnp.put with mode='wrap' on size-6 array:", target2)

1D array: [10 20 30 40 50 60]

np.take(arr, [0,2,5], axis=None): [10 30 60]
arr[[0,2,5]] (fancy):             [10 30 60]
Same result: True

2D matrix:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

np.take(mat, [0,2], axis=0) — pick rows:
 [[ 1  2  3  4]
 [ 9 10 11 12]]
Shape: (2, 4)

np.take(mat, [1,3], axis=1) — pick columns:
 [[ 2  4]
 [ 6  8]
 [10 12]]
Shape: (3, 2)

np.take with mode='wrap', indices [0,7,-1]: [10 20 60]
(index 7 wraps to position 1, -1 wraps to position 5)

Before np.put: [0 0 0 0 0 0 0 0]
After np.put(target, [1,3,6], [99,88,77]): [ 0 99  0 88  0  0 77  0]

np.put with mode='wrap' on size-6 array: [11 33  0  0  0  0]


### How it works

- `np.take(arr, indices)` gathers elements at given positions — like fancy indexing but with extra options.
- With `axis=None` (default), the array is treated as flat regardless of shape — useful on 2D arrays without manually ravelling.
- With `axis=0` or `axis=1`, `np.take` picks whole rows or columns, equivalent to `mat[[0,2], :]` or `mat[:, [1,3]]`.
- **Key difference from fancy indexing:** `np.take` supports `mode='wrap'` — out-of-bounds indices wrap around like a circular buffer instead of raising an error.
- `np.put(arr, indices, values)` is the reverse — it **scatters** values into flat positions in-place, modifying the original array directly.
- `np.put` also supports `mode='wrap'`, so index `7` on a size-6 array writes to position `1`.

**Key takeaway:** `np.take` is fancy indexing with axis control and wrap mode; `np.put` is its in-place scatter counterpart — use them when you need index wrapping or explicit axis-based gathering that plain fancy indexing does not express as cleanly.

### Q17. `np.compress`
Given a 2D array of shape `(5, 4)`, use `np.compress` with a boolean condition array to select specific rows (axis=0) and specific columns (axis=1). Compare this to equivalent boolean indexing and note when `compress` is preferred.

In [17]:
# Q17: np.compress for row and column selection on a 2D array

import numpy as np

mat = np.arange(1, 21).reshape(5, 4)
print("Matrix:\n", mat)
print("Shape:", mat.shape)              # (5, 4)

# -----------------------------------------------------------------------
# np.compress along axis=0 — select rows where condition is True
# -----------------------------------------------------------------------
row_condition = [True, False, True, False, True]   # keep rows 0, 2, 4
rows_compress = np.compress(row_condition, mat, axis=0)
print("\nnp.compress rows [T,F,T,F,T] axis=0:\n", rows_compress)
print("Shape:", rows_compress.shape)    # (3, 4)

# Equivalent boolean indexing
mask = np.array(row_condition)
rows_bool = mat[mask, :]
print("\nBoolean indexing mat[mask, :]:\n", rows_bool)
print("Results match:", np.array_equal(rows_compress, rows_bool))

# -----------------------------------------------------------------------
# np.compress along axis=1 — select columns where condition is True
# -----------------------------------------------------------------------
col_condition = [False, True, False, True]         # keep cols 1 and 3
cols_compress = np.compress(col_condition, mat, axis=1)
print("\nnp.compress cols [F,T,F,T] axis=1:\n", cols_compress)
print("Shape:", cols_compress.shape)    # (5, 2)

# Equivalent boolean indexing
cols_bool = mat[:, np.array(col_condition)]
print("\nBoolean indexing mat[:, mask]:\n", cols_bool)
print("Results match:", np.array_equal(cols_compress, cols_bool))

# -----------------------------------------------------------------------
# np.compress with axis=None — flattens first, then filters
# -----------------------------------------------------------------------
flat_condition = np.array([1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0], dtype=bool)
flat_result = np.compress(flat_condition, mat)     # treats mat as 1D
print("\nnp.compress on flattened (every other element):", flat_result)

Matrix:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]
Shape: (5, 4)

np.compress rows [T,F,T,F,T] axis=0:
 [[ 1  2  3  4]
 [ 9 10 11 12]
 [17 18 19 20]]
Shape: (3, 4)

Boolean indexing mat[mask, :]:
 [[ 1  2  3  4]
 [ 9 10 11 12]
 [17 18 19 20]]
Results match: True

np.compress cols [F,T,F,T] axis=1:
 [[ 2  4]
 [ 6  8]
 [10 12]
 [14 16]
 [18 20]]
Shape: (5, 2)

Boolean indexing mat[:, mask]:
 [[ 2  4]
 [ 6  8]
 [10 12]
 [14 16]
 [18 20]]
Results match: True

np.compress on flattened (every other element): [ 1  3  5  7  9 11 13 15 17 19]


### How it works

- `np.compress(condition, arr, axis)` selects slices along the given axis wherever the condition is `True` — it is boolean indexing expressed as a function call.
- `axis=0` filters **rows**: the condition length must equal the number of rows.
- `axis=1` filters **columns**: the condition length must equal the number of columns.
- With `axis=None`, the array is flattened first and the condition selects individual elements.
- The result is identical to boolean indexing — `np.array_equal` confirms this in both cases.
- **When is `np.compress` preferred?** It is cleaner when the condition array is already computed and you want to pass array + condition + axis as a single readable function call, especially inside pipelines or when applying the same condition to multiple arrays without repeating the indexing syntax.

**Key takeaway:** `np.compress` is boolean indexing in function form — same result, but explicit `axis` argument makes the intent (filter rows vs columns) immediately visible without needing comma syntax like `mat[mask, :]`.

### Q18. Multi-Dimensional Fancy Indexing
Create a 3D array of shape `(3, 4, 5)`. Demonstrate indexing with:
- A single integer per axis: `arr[1, 2, 3]`
- Mixed slices and integers: `arr[1, :, 2:4]`
- Fancy indexing on the first axis while slicing others: `arr[[0, 2], 1:3, :]`
Print each result's shape and explain it.

In [18]:
# Q18: Multi-dimensional indexing on a 3D array (3, 4, 5)

import numpy as np

arr = np.arange(60).reshape(3, 4, 5)
print("Array shape:", arr.shape)        # (3, 4, 5)
print("Array:\n", arr)

# -----------------------------------------------------------------------
# Single integer per axis — collapses all three axes → scalar
# -----------------------------------------------------------------------
scalar = arr[1, 2, 3]
print("\narr[1, 2, 3]:", scalar)
print("Type:", type(scalar))            # numpy scalar, not array
print("Shape: () — all axes collapsed to a single value")

# -----------------------------------------------------------------------
# Mixed slice and integer — integer collapses its axis, slice keeps it
# -----------------------------------------------------------------------
mixed = arr[1, :, 2:4]
print("\narr[1, :, 2:4]:")
print(mixed)
print("Shape:", mixed.shape)            # (4, 2)
# axis 0 → int 1    → collapsed (removed)
# axis 1 → :        → kept, size 4
# axis 2 → 2:4      → kept, size 2  → result (4, 2)

# -----------------------------------------------------------------------
# Fancy indexing on first axis, slicing on others
# -----------------------------------------------------------------------
fancy = arr[[0, 2], 1:3, :]
print("\narr[[0, 2], 1:3, :]:")
print(fancy)
print("Shape:", fancy.shape)            # (2, 2, 5)
# axis 0 → [0,2]    → fancy index picks 2 slabs → size 2
# axis 1 → 1:3      → slice keeps 2 rows        → size 2
# axis 2 → :        → all 5 columns kept        → size 5 → result (2, 2, 5)

# -----------------------------------------------------------------------
# Summary table
# -----------------------------------------------------------------------
print("\n--- Shape summary ---")
print(f"arr[1, 2, 3]          → shape {np.shape(scalar)} (scalar)")
print(f"arr[1, :, 2:4]        → shape {mixed.shape}")
print(f"arr[[0,2], 1:3, :]    → shape {fancy.shape}")

Array shape: (3, 4, 5)
Array:
 [[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]
  [30 31 32 33 34]
  [35 36 37 38 39]]

 [[40 41 42 43 44]
  [45 46 47 48 49]
  [50 51 52 53 54]
  [55 56 57 58 59]]]

arr[1, 2, 3]: 33
Type: <class 'numpy.int64'>
Shape: () — all axes collapsed to a single value

arr[1, :, 2:4]:
[[22 23]
 [27 28]
 [32 33]
 [37 38]]
Shape: (4, 2)

arr[[0, 2], 1:3, :]:
[[[ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[45 46 47 48 49]
  [50 51 52 53 54]]]
Shape: (2, 2, 5)

--- Shape summary ---
arr[1, 2, 3]          → shape () (scalar)
arr[1, :, 2:4]        → shape (4, 2)
arr[[0,2], 1:3, :]    → shape (2, 2, 5)


### How it works

- A 3D array has three axes. Each index position in `arr[ax0, ax1, ax2]` controls one axis independently.
- **Integer index** on an axis: that axis is **collapsed** and disappears from the output shape.
- **Slice** on an axis: that axis is **kept**, sized by the slice length.
- **Fancy index** (list) on an axis: that axis is **kept**, sized by the number of indices in the list.

Applying these rules to each case:

| Expression | axis 0 | axis 1 | axis 2 | Output shape |
|---|---|---|---|---|
| `arr[1, 2, 3]` | int → gone | int → gone | int → gone | `()` scalar |
| `arr[1, :, 2:4]` | int → gone | `:` → 4 | `2:4` → 2 | `(4, 2)` |
| `arr[[0,2], 1:3, :]` | `[0,2]` → 2 | `1:3` → 2 | `:` → 5 | `(2, 2, 5)` |

**Key takeaway:** The output shape is built by keeping only the axes that were indexed with a slice or fancy list — integer indices remove their axis entirely; count what remains to predict the result shape.

### Q19. Assigning to Slices and Fancy Indices
Create a 5×5 matrix of zeros. Using assignment to slices and fancy indices:
- Set the diagonal to 1 (without `np.fill_diagonal`)
- Set the top-right 2×2 corner to 9
- Set the last column to values `[10, 20, 30, 40, 50]`
- Set rows 1 and 3 to all 7s using fancy index assignment
Print the final matrix.

In [19]:
# Q19: Assigning to slices and fancy indices on a 5x5 zero matrix

import numpy as np

mat = np.zeros((5, 5), dtype=int)
print("Initial matrix:\n", mat)

# Set diagonal to 1 — paired fancy indices (0,0),(1,1),(2,2),(3,3),(4,4)
idx = [0, 1, 2, 3, 4]
mat[idx, idx] = 1
print("\nAfter setting diagonal to 1:\n", mat)

# Set top-right 2x2 corner to 9 — rows 0:2, cols 3:5
mat[0:2, 3:5] = 9
print("\nAfter setting top-right 2x2 to 9:\n", mat)

# Set last column to [10,20,30,40,50] — all rows, col index -1
mat[:, -1] = [10, 20, 30, 40, 50]
print("\nAfter setting last column to [10..50]:\n", mat)

# Set rows 1 and 3 to all 7s — fancy row index assignment
mat[[1, 3], :] = 7
print("\nAfter setting rows 1 and 3 to 7:\n", mat)

Initial matrix:
 [[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]

After setting diagonal to 1:
 [[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]

After setting top-right 2x2 to 9:
 [[1 0 0 9 9]
 [0 1 0 9 9]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]

After setting last column to [10..50]:
 [[ 1  0  0  9 10]
 [ 0  1  0  9 20]
 [ 0  0  1  0 30]
 [ 0  0  0  1 40]
 [ 0  0  0  0 50]]

After setting rows 1 and 3 to 7:
 [[ 1  0  0  9 10]
 [ 7  7  7  7  7]
 [ 0  0  1  0 30]
 [ 7  7  7  7  7]
 [ 0  0  0  0 50]]


### How it works

- **Diagonal:** paired index arrays `mat[[0,1,2,3,4], [0,1,2,3,4]]` selects positions `(0,0),(1,1),...` — assigning `1` writes to each diagonal cell individually.
- **Top-right 2×2:** `mat[0:2, 3:5]` is a standard 2D slice; assigning a scalar fills all 4 cells at once.
- **Last column:** `mat[:, -1]` selects every row in column `-1`; assigning a 1D array of length 5 maps one value per row.
- **Rows 1 and 3:** `mat[[1, 3], :]` is fancy index assignment — NumPy writes `7` across all columns of both selected rows in one step.
- Assignment order matters here: rows 1 and 3 overwrite whatever diagonal or corner values were set there earlier.

**Key takeaway:** Any valid index expression (slice, fancy, boolean) can appear on the **left side** of `=` — NumPy writes values into exactly those positions, broadcasting a scalar or matching a 1D array automatically.

### Q20. Strided Access with `np.lib.stride_tricks`
Use `np.lib.stride_tricks.as_strided` to create a sliding-window view of a 1D array. Given `arr = np.arange(10)` and window size 4, create a 2D array of shape `(7, 4)` where each row is a window of 4 consecutive elements. Explain how `strides` determine this. Add a warning comment about safety.

In [20]:
# Q20: Sliding window view using np.lib.stride_tricks.as_strided

import numpy as np

arr = np.arange(10)
print("Original array:", arr)
print("Shape:", arr.shape)              # (10,)
print("Dtype:", arr.dtype)              # int64

# Each element is 8 bytes (int64); stride of the original array
elem_size = arr.strides[0]             # bytes to step to next element
print("\nBytes per element:", elem_size)  # 8

# Sliding window parameters
window_size = 4
n_windows    = len(arr) - window_size + 1   # 10 - 4 + 1 = 7
print("Number of windows:", n_windows)       # 7
print("Window size:", window_size)

# as_strided: shape=(7,4), strides=(8,8)
# row stride = 8  → move 1 element forward to start next window
# col stride = 8  → move 1 element forward within a window
# WARNING: as_strided does NOT bounds-check — wrong strides can read
# memory outside the array, causing silent corruption or crashes.
# Always verify (n_windows, window_size) manually before calling.
windows = np.lib.stride_tricks.as_strided(
    arr,
    shape=(n_windows, window_size),
    strides=(elem_size, elem_size)      # (step between windows, step within window)
)
print("\nSliding window view (shape 7×4):\n", windows)
print("Shape:", windows.shape)          # (7, 4)

# Confirm each row is 4 consecutive elements starting at row index i
print("\nManual check:")
for i in range(n_windows):
    print(f"  Row {i}: {windows[i]} == arr[{i}:{i+window_size}] {arr[i:i+window_size]}",
          "✓" if np.array_equal(windows[i], arr[i:i+window_size]) else "✗")

# Safe modern alternative (NumPy 1.20+) — no manual stride calculation needed
safe_windows = np.lib.stride_tricks.sliding_window_view(arr, window_shape=4)
print("\nsliding_window_view result:\n", safe_windows)
print("Matches as_strided:", np.array_equal(windows, safe_windows))

Original array: [0 1 2 3 4 5 6 7 8 9]
Shape: (10,)
Dtype: int64

Bytes per element: 8
Number of windows: 7
Window size: 4

Sliding window view (shape 7×4):
 [[0 1 2 3]
 [1 2 3 4]
 [2 3 4 5]
 [3 4 5 6]
 [4 5 6 7]
 [5 6 7 8]
 [6 7 8 9]]
Shape: (7, 4)

Manual check:
  Row 0: [0 1 2 3] == arr[0:4] [0 1 2 3] ✓
  Row 1: [1 2 3 4] == arr[1:5] [1 2 3 4] ✓
  Row 2: [2 3 4 5] == arr[2:6] [2 3 4 5] ✓
  Row 3: [3 4 5 6] == arr[3:7] [3 4 5 6] ✓
  Row 4: [4 5 6 7] == arr[4:8] [4 5 6 7] ✓
  Row 5: [5 6 7 8] == arr[5:9] [5 6 7 8] ✓
  Row 6: [6 7 8 9] == arr[6:10] [6 7 8 9] ✓

sliding_window_view result:
 [[0 1 2 3]
 [1 2 3 4]
 [2 3 4 5]
 [3 4 5 6]
 [4 5 6 7]
 [5 6 7 8]
 [6 7 8 9]]
Matches as_strided: True


### How it works

- Every NumPy array stores `strides` — the number of **bytes** to step in memory to move one position along each axis.
- `arr = np.arange(10)` with `int64` dtype has stride `(8,)` — one element = 8 bytes.
- `as_strided(arr, shape=(7,4), strides=(8,8))` tells NumPy: to move to the next **row**, step 8 bytes (one element); to move to the next **column**, also step 8 bytes.
- This means row `i` starts at byte offset `i×8` and reads 4 consecutive elements — a sliding window of size 4, moving one element at a time.
- Result shape `(7, 4)` comes from `n_windows = 10 - 4 + 1 = 7` rows, 4 columns each.
- **Safety warning:** `as_strided` bypasses all bounds checking — wrong shape or stride values silently read memory outside the array. Always prefer `np.lib.stride_tricks.sliding_window_view` (NumPy 1.20+) which computes strides safely for you.

**Key takeaway:** Strides control how NumPy walks memory — by setting both row and column stride to one element size, `as_strided` creates overlapping windows with zero data copying, but use `sliding_window_view` in practice to avoid unsafe manual stride arithmetic.

### Q21. `np.where` with Multidimensional Arrays
Create a 4×4 matrix of random integers. Use `np.where(condition)` (no x/y arguments) to get the row and column indices of all elements greater than 50. Then use `np.where(condition, x, y)` to create a new matrix where elements above 50 are replaced with their value, and others with -1.

In [21]:
# Q21: np.where with and without x/y arguments on a 4x4 matrix

import numpy as np

rng = np.random.default_rng(99)
mat = rng.integers(0, 101, size=(4, 4))
print("Matrix:\n", mat)
print("Shape:", mat.shape)

# -----------------------------------------------------------------------
# np.where(condition) — no x/y: returns tuple of index arrays
# -----------------------------------------------------------------------
condition = mat > 50
row_idx, col_idx = np.where(condition)
print("\nElements > 50:")
print("  Row indices:", row_idx)
print("  Col indices:", col_idx)
print("  Values at those positions:", mat[row_idx, col_idx])

# Zip together for readable (row, col, value) view
print("\n  (row, col) → value:")
for r, c in zip(row_idx, col_idx):
    print(f"    ({r}, {c}) → {mat[r, c]}")

# -----------------------------------------------------------------------
# np.where(condition, x, y) — element-wise selector
# keep value where True, put -1 where False
# -----------------------------------------------------------------------
result = np.where(condition, mat, -1)
print("\nnp.where(mat > 50, mat, -1):\n", result)
print("Shape:", result.shape)           # (4, 4) — same as input

# Quick verification — no value in result should be in (0, 50]
print("\nAll non-(-1) values are > 50:",
      np.all((result == -1) | (result > 50)))

Matrix:
 [[96 51 76 57]
 [17 51 95 98]
 [97 62 31 57]
 [65 28 97 56]]
Shape: (4, 4)

Elements > 50:
  Row indices: [0 0 0 0 1 1 1 2 2 2 3 3 3]
  Col indices: [0 1 2 3 1 2 3 0 1 3 0 2 3]
  Values at those positions: [96 51 76 57 51 95 98 97 62 57 65 97 56]

  (row, col) → value:
    (0, 0) → 96
    (0, 1) → 51
    (0, 2) → 76
    (0, 3) → 57
    (1, 1) → 51
    (1, 2) → 95
    (1, 3) → 98
    (2, 0) → 97
    (2, 1) → 62
    (2, 3) → 57
    (3, 0) → 65
    (3, 2) → 97
    (3, 3) → 56

np.where(mat > 50, mat, -1):
 [[96 51 76 57]
 [-1 51 95 98]
 [97 62 -1 57]
 [65 -1 97 56]]
Shape: (4, 4)

All non-(-1) values are > 50: True


### How it works

- `np.where(condition)` with **no x/y** returns a tuple of index arrays — one per axis. For a 2D array, `(row_idx, col_idx)` gives the coordinates of every `True` position. This is equivalent to `np.argwhere(condition).T`.
- Passing both index arrays into `mat[row_idx, col_idx]` then retrieves the actual values using fancy indexing.
- `np.where(condition, x, y)` with **x and y** is an element-wise ternary: where condition is `True`, take from `x`; where `False`, take from `y`. Both `x` and `y` broadcast against the condition.
- Using `mat` as `x` and `-1` as `y` keeps original values above 50 and fills everything else with `-1`.
- The scalar `-1` broadcasts to the full `(4, 4)` shape automatically.

**Key takeaway:** `np.where(condition)` is an index finder — use it to locate positions; `np.where(condition, x, y)` is an element-wise selector — use it to build a new array by choosing between two sources at every position.

### Q22. `np.unravel_index` and `np.ravel_multi_index`
Given a 4×5 array, find the flat index of the maximum element with `argmax()`. Convert it to 2D row/column indices using `np.unravel_index`. Then convert back to a flat index using `np.ravel_multi_index`. Verify the round-trip.

In [22]:
# Q22: np.unravel_index and np.ravel_multi_index round-trip

import numpy as np

rng = np.random.default_rng(55)
mat = rng.integers(0, 100, size=(4, 5))
print("Matrix:\n", mat)
print("Shape:", mat.shape)              # (4, 5)

# -----------------------------------------------------------------------
# Step 1: find flat index of the maximum element
# -----------------------------------------------------------------------
flat_idx = np.argmax(mat)              # treats array as flattened
print("\nFlat index of max (argmax):", flat_idx)
print("Max value:", mat.flat[flat_idx])

# -----------------------------------------------------------------------
# Step 2: flat index → (row, col) using np.unravel_index
# -----------------------------------------------------------------------
row, col = np.unravel_index(flat_idx, shape=mat.shape)
print("\nnp.unravel_index →")
print("  Row:", row)
print("  Col:", col)
print("  mat[row, col]:", mat[row, col])   # must match max value

# -----------------------------------------------------------------------
# Step 3: (row, col) → flat index using np.ravel_multi_index
# -----------------------------------------------------------------------
flat_back = np.ravel_multi_index((row, col), dims=mat.shape)
print("\nnp.ravel_multi_index → flat index:", flat_back)

# -----------------------------------------------------------------------
# Round-trip verification
# -----------------------------------------------------------------------
print("\nRound-trip check:")
print("  Original flat index :", flat_idx)
print("  Recovered flat index:", flat_back)
print("  Match:", flat_idx == flat_back)

# -----------------------------------------------------------------------
# Bonus: unravel multiple flat indices at once
# -----------------------------------------------------------------------
top3_flat = np.argsort(mat.ravel())[-3:][::-1]   # flat indices of top 3 values
rows, cols = np.unravel_index(top3_flat, shape=mat.shape)
print("\nTop 3 values and their positions:")
for r, c, f in zip(rows, cols, top3_flat):
    print(f"  flat={f} → ({r},{c}) → value={mat[r, c]}")
    

Matrix:
 [[96 83 72 87 22]
 [21 78 23 58 49]
 [33 75 50 70 11]
 [94 78  6 69 49]]
Shape: (4, 5)

Flat index of max (argmax): 0
Max value: 96

np.unravel_index →
  Row: 0
  Col: 0
  mat[row, col]: 96

np.ravel_multi_index → flat index: 0

Round-trip check:
  Original flat index : 0
  Recovered flat index: 0
  Match: True

Top 3 values and their positions:
  flat=0 → (0,0) → value=96
  flat=15 → (3,0) → value=94
  flat=3 → (0,3) → value=87


### How it works

- NumPy stores data in a flat (1D) block of memory. A flat index counts elements left-to-right, top-to-bottom across the entire array.
- `np.argmax(mat)` returns the **flat** index of the largest value — as if the array were a single long list.
- `np.unravel_index(flat_idx, shape)` converts that flat index back into per-axis indices using the shape. For a `(4, 5)` array, flat index `f` maps to row `f // 5` and col `f % 5`.
- `np.ravel_multi_index((row, col), dims=shape)` reverses the process: `row * 5 + col` gives back the flat index.
- Both functions accept arrays of indices, so you can convert many positions at once — the bonus section shows this for the top 3 values.

**Key takeaway:** `np.unravel_index` and `np.ravel_multi_index` are inverses — one converts flat → multi-dimensional coordinates, the other converts back; together they let you work in whichever index space is more convenient.

### Q23. Boolean Mask — Image-Style Operations
Create a 10×10 array representing a grayscale "image" (random integers 0–255). Use boolean masking to:
- Threshold the image: set pixels below 128 to 0 and above to 255 (binarize)
- Brighten only the dark pixels (below 100): add 50, capped at 255 using `np.clip`
- Count the proportion of "bright" pixels (above 200)

In [23]:
# Q23: Boolean mask image-style operations on a 10x10 grayscale array

import numpy as np

rng = np.random.default_rng(12)
image = rng.integers(0, 256, size=(10, 10))
print("Grayscale image:\n", image)
print("Shape:", image.shape)            # (10, 10)

# -----------------------------------------------------------------------
# Operation 1: Binarize — pixels < 128 → 0, pixels >= 128 → 255
# -----------------------------------------------------------------------
binary = np.where(image >= 128, 255, 0)
print("\nBinarized image (< 128 → 0, >= 128 → 255):\n", binary)

dark_count   = np.sum(binary == 0)
bright_count = np.sum(binary == 255)
print(f"Dark pixels: {dark_count}  |  Bright pixels: {bright_count}")

# -----------------------------------------------------------------------
# Operation 2: Brighten dark pixels (< 100) by +50, capped at 255
# -----------------------------------------------------------------------
brightened = image.copy()
dark_mask = brightened < 100           # boolean mask — True where pixel is dark
brightened[dark_mask] = np.clip(brightened[dark_mask] + 50, 0, 255)
print("\nAfter brightening dark pixels (< 100) by +50:\n", brightened)

# Verify — no brightened pixel (that was dark) should exceed 255
print("Max value after brightening:", brightened.max())   # must be <= 255

# Side-by-side comparison of changed pixels
changed = dark_mask                    # pixels that were modified
print("\nOriginal vs brightened for dark pixels:")
print("  Before:", image[changed])
print("  After: ", brightened[changed])

# -----------------------------------------------------------------------
# Operation 3: Proportion of bright pixels (> 200) in original image
# -----------------------------------------------------------------------
bright_mask = image > 200
bright_proportion = bright_mask.mean()   # mean of bool array = fraction of True
print(f"\nProportion of bright pixels (> 200): {bright_proportion:.2%}")
print(f"Count: {bright_mask.sum()} out of {image.size} pixels")

Grayscale image:
 [[156  64 249 242  16  48  51  45 148  89]
 [123  59 243 171 170  29  40 229  80 219]
 [201   0 121 138 119  27 184  66  89 106]
 [ 76 116 214 119 189 237  55  66 142  48]
 [176 171 173 242 108 236 249 225  77  16]
 [220 239  84 166  43 223 217 104 200  56]
 [248 203 208 169  12 199 182  51 219  34]
 [102 195 198   5  64 242 144  34  87 153]
 [  0 107  64  82 161  43 234 199 166 234]
 [ 21 186 227 153 139 182 185 137 136 142]]
Shape: (10, 10)

Binarized image (< 128 → 0, >= 128 → 255):
 [[255   0 255 255   0   0   0   0 255   0]
 [  0   0 255 255 255   0   0 255   0 255]
 [255   0   0 255   0   0 255   0   0   0]
 [  0   0 255   0 255 255   0   0 255   0]
 [255 255 255 255   0 255 255 255   0   0]
 [255 255   0 255   0 255 255   0 255   0]
 [255 255 255 255   0 255 255   0 255   0]
 [  0 255 255   0   0 255 255   0   0 255]
 [  0   0   0   0 255   0 255 255 255 255]
 [  0 255 255 255 255 255 255 255 255 255]]
Dark pixels: 45  |  Bright pixels: 55

After brightening da

### How it works

- **Binarize:** `np.where(image >= 128, 255, 0)` is an element-wise ternary — every pixel gets either 255 or 0 in one expression, no loop needed.
- **Brighten dark pixels:** `dark_mask = image < 100` creates a boolean mask; `brightened[dark_mask] += 50` adds 50 only to those positions. `np.clip(..., 0, 255)` ensures no value overflows the 0–255 byte range.
- **Proportion of bright pixels:** A boolean array contains `True=1` and `False=0`. Taking `.mean()` on it gives the fraction of `True` values — a clean one-liner for counting proportions without an explicit `sum / total`.
- All three operations work on the full 10×10 array at once — no Python loops needed.

**Key takeaway:** Boolean masks are the core tool for image processing in NumPy — create a mask from a condition, use it to read, write, or count pixels selectively, and combine with `np.where` / `np.clip` for capped or branching transformations.

### Q24. Combining Fancy Indexing and Broadcasting
Given a 2D array `data` of shape `(10, 6)` representing 10 students' scores on 6 subjects, and a weights array of shape `(6,)`, use fancy indexing to select rows 0, 2, 5, 7 and then apply a weighted mean (broadcasting the weights across selected rows) — all without loops.

In [24]:
# Q24: Fancy indexing + broadcasting for weighted mean across selected students

import numpy as np

rng = np.random.default_rng(33)
data    = rng.integers(40, 101, size=(10, 6))   # 10 students, 6 subjects
weights = np.array([0.10, 0.15, 0.20, 0.20, 0.15, 0.20])  # must sum to 1.0
print("Student scores (10×6):\n", data)
print("\nSubject weights:", weights)
print("Weights sum to:", weights.sum())          # confirm = 1.0

# -----------------------------------------------------------------------
# Step 1: fancy indexing — select rows 0, 2, 5, 7
# -----------------------------------------------------------------------
selected_rows = [0, 2, 5, 7]
selected = data[selected_rows, :]               # shape (4, 6)
print("\nSelected students (rows 0,2,5,7):\n", selected)
print("Shape:", selected.shape)                  # (4, 6)

# -----------------------------------------------------------------------
# Step 2: apply weights — broadcasting (4,6) * (6,) → (4,6)
# -----------------------------------------------------------------------
weighted = selected * weights                    # each column scaled by its weight
print("\nWeighted scores:\n", np.round(weighted, 2))
print("Shape:", weighted.shape)                  # (4, 6)

# -----------------------------------------------------------------------
# Step 3: sum across subjects (axis=1) → weighted mean per student
# -----------------------------------------------------------------------
weighted_means = weighted.sum(axis=1)            # shape (4,)
print("\nWeighted mean per selected student:", np.round(weighted_means, 2))

# -----------------------------------------------------------------------
# One-liner combining all three steps
# -----------------------------------------------------------------------
result = (data[[0, 2, 5, 7]] * weights).sum(axis=1)
print("\nOne-liner result:", np.round(result, 2))
print("Matches step-by-step:", np.allclose(weighted_means, result))

# -----------------------------------------------------------------------
# Bonus: rank selected students by weighted mean
# -----------------------------------------------------------------------
rank_order = np.argsort(result)[::-1]           # descending
print("\nStudent ranking (best → worst):")
for rank, idx in enumerate(rank_order):
    student_id = selected_rows[idx]
    print(f"  Rank {rank+1}: Student {student_id}  weighted mean = {result[idx]:.2f}")

Student scores (10×6):
 [[93 67 63 74 90 95]
 [58 55 72 75 55 61]
 [96 86 92 73 63 52]
 [81 71 65 54 70 43]
 [43 46 92 60 47 40]
 [97 87 49 89 75 41]
 [47 72 82 66 49 64]
 [92 44 79 97 77 58]
 [54 96 80 64 46 52]
 [67 55 55 55 51 89]]

Subject weights: [0.1  0.15 0.2  0.2  0.15 0.2 ]
Weights sum to: 1.0

Selected students (rows 0,2,5,7):
 [[93 67 63 74 90 95]
 [96 86 92 73 63 52]
 [97 87 49 89 75 41]
 [92 44 79 97 77 58]]
Shape: (4, 6)

Weighted scores:
 [[ 9.3  10.05 12.6  14.8  13.5  19.  ]
 [ 9.6  12.9  18.4  14.6   9.45 10.4 ]
 [ 9.7  13.05  9.8  17.8  11.25  8.2 ]
 [ 9.2   6.6  15.8  19.4  11.55 11.6 ]]
Shape: (4, 6)

Weighted mean per selected student: [79.25 75.35 69.8  74.15]

One-liner result: [79.25 75.35 69.8  74.15]
Matches step-by-step: True

Student ranking (best → worst):
  Rank 1: Student 0  weighted mean = 79.25
  Rank 2: Student 2  weighted mean = 75.35
  Rank 3: Student 7  weighted mean = 74.15
  Rank 4: Student 5  weighted mean = 69.80


### How it works

- `data[[0, 2, 5, 7], :]` uses fancy indexing to pick exactly 4 rows — result shape is `(4, 6)`.
- Multiplying `(4, 6) * (6,)` triggers broadcasting: the weights array is treated as `(1, 6)` and stretched across all 4 rows, scaling each subject column by its weight independently.
- `.sum(axis=1)` then collapses the 6 subjects into a single weighted total per student — shape becomes `(4,)`.
- Because weights sum to 1.0, this sum is already a weighted mean — no division needed.
- `np.argsort(result)[::-1]` gives the ranking: `argsort` returns indices that would sort ascending, `[::-1]` reverses to descending.

**Key takeaway:** Fancy indexing and broadcasting compose cleanly — select the rows you need first, then multiply by weights (which broadcast across columns automatically), then reduce with `.sum(axis=1)` to get one value per row, all without a single loop.

### Q25. Challenge — Vectorized k-Nearest Neighbors Distance Matrix
Given two sets of points: `A` of shape `(50, 2)` and `B` of shape `(30, 2)`, compute the full Euclidean distance matrix `D` of shape `(50, 30)` where `D[i, j]` is the distance from `A[i]` to `B[j]` — **entirely using broadcasting, no loops**. Then:
- Find the nearest point in B for each point in A (argmin along axis=1)
- Find all pairs with distance less than a threshold of 0.5
- Find the point in A with the largest minimum distance to any point in B (the most isolated point)
This is the core computation behind kNN classification.

In [25]:
# Q25: Vectorized Euclidean distance matrix using broadcasting — kNN foundation

import numpy as np

rng = np.random.default_rng(77)
A = rng.random((50, 2))               # 50 points in 2D, shape (50, 2)
B = rng.random((30, 2))               # 30 points in 2D, shape (30, 2)
print("A shape:", A.shape)            # (50, 2)
print("B shape:", B.shape)            # (30, 2)

# -----------------------------------------------------------------------
# Step 1: build full (50, 30) distance matrix — no loops
#
# A[:, np.newaxis, :]  → (50,  1, 2)
# B[np.newaxis, :, :]  → ( 1, 30, 2)
# diff                 → (50, 30, 2)  via broadcasting
# -----------------------------------------------------------------------
diff = A[:, np.newaxis, :] - B[np.newaxis, :, :]   # (50, 30, 2)
D    = np.sqrt((diff ** 2).sum(axis=2))             # (50, 30) — L2 norm
print("\nDistance matrix D shape:", D.shape)        # (50, 30)
print("Sample distances D[0, :5]:", np.round(D[0, :5], 4))

# -----------------------------------------------------------------------
# Step 2: nearest point in B for each point in A
# -----------------------------------------------------------------------
nearest_b_idx = np.argmin(D, axis=1)               # shape (50,) — one index per A point
nearest_b_dist = D[np.arange(50), nearest_b_idx]   # shape (50,) — actual distances
print("\nNearest B index for each A point (first 10):", nearest_b_idx[:10])
print("Nearest B distance for each A point (first 10):", np.round(nearest_b_dist[:10], 4))

# -----------------------------------------------------------------------
# Step 3: all pairs with distance < threshold
# -----------------------------------------------------------------------
threshold = 0.5
close_mask        = D < threshold                   # shape (50, 30) boolean
close_a, close_b  = np.where(close_mask)            # row and col indices of True
print(f"\nPairs with distance < {threshold}: {len(close_a)} pairs")
print("First 5 close pairs (A_idx, B_idx, distance):")
for a_i, b_i in zip(close_a[:5], close_b[:5]):
    print(f"  A[{a_i:2d}] ↔ B[{b_i:2d}]  dist = {D[a_i, b_i]:.4f}")

# -----------------------------------------------------------------------
# Step 4: most isolated point in A
# (largest minimum distance to any B point)
# -----------------------------------------------------------------------
min_dist_to_B  = D.min(axis=1)                     # shape (50,) — closest B for each A
most_isolated  = np.argmax(min_dist_to_B)           # A index with largest min distance
print(f"\nMost isolated point in A:")
print(f"  A index : {most_isolated}")
print(f"  Location: {A[most_isolated]}")
print(f"  Min dist to any B point: {min_dist_to_B[most_isolated]:.4f}")

# -----------------------------------------------------------------------
# Sanity check: compare one distance to manual formula
# -----------------------------------------------------------------------
i, j = 3, 7
manual = np.sqrt(((A[i] - B[j]) ** 2).sum())
print(f"\nSanity check D[{i},{j}]: broadcast={D[i,j]:.6f}  manual={manual:.6f}  match={np.isclose(D[i,j], manual)}")

A shape: (50, 2)
B shape: (30, 2)

Distance matrix D shape: (50, 30)
Sample distances D[0, :5]: [0.6061 0.5497 0.5989 0.4317 0.6549]

Nearest B index for each A point (first 10): [ 6  0  3 17 26 27  0 15 17 17]
Nearest B distance for each A point (first 10): [0.0557 0.0616 0.0894 0.07   0.0227 0.0196 0.0765 0.1557 0.0802 0.0912]

Pairs with distance < 0.5: 682 pairs
First 5 close pairs (A_idx, B_idx, distance):
  A[ 0] ↔ B[ 3]  dist = 0.4317
  A[ 0] ↔ B[ 6]  dist = 0.0557
  A[ 0] ↔ B[ 7]  dist = 0.1361
  A[ 0] ↔ B[12]  dist = 0.2350
  A[ 0] ↔ B[13]  dist = 0.2795

Most isolated point in A:
  A index : 14
  Location: [0.00284069 0.46162128]
  Min dist to any B point: 0.2166

Sanity check D[3,7]: broadcast=0.589058  manual=0.589058  match=True


### How it works

- The key trick is dimension expansion before subtraction: `A[:, np.newaxis, :]` lifts A to `(50, 1, 2)` and `B[np.newaxis, :, :]` lifts B to `(1, 30, 2)`. Broadcasting stretches both to `(50, 30, 2)` — every pair `(i, j)` gets its own difference vector with no loop.
- `.sum(axis=2)` collapses the 2 coordinate dimensions, leaving squared distances of shape `(50, 30)`. `np.sqrt` gives the final Euclidean distance matrix.
- `np.argmin(D, axis=1)` finds the column index of the smallest value in each row — the nearest B point for each A point.
- `D < threshold` produces a `(50, 30)` boolean mask; `np.where` extracts the `(row, col)` coordinates of every `True` cell — all close pairs at once.
- `D.min(axis=1)` gives each A point's distance to its nearest B neighbour; `np.argmax` of that finds the A point whose nearest neighbour is furthest away — the most isolated point.

**Key takeaway:** The entire kNN distance matrix is built in three broadcasting lines — expand dims to `(50,1,2)` and `(1,30,2)`, subtract to get `(50,30,2)` difference vectors, then reduce with `.sum(axis=2)` and `sqrt`; every subsequent kNN query (nearest neighbour, threshold search, isolation) is then just a mask or argmin on that matrix.